sign-commit                = true
sign-tag                   = true
no-dev-version             = true
consolidate-commits        = true
pre-release-commit-message = "Prepare to release"
tag-message                = "Bump version to v{{version}}"
tag-prefix                 = ""
dependent-version          = "upgrade"
pre-release-replacements = [
    {file ="Cargo.toml", search="version = \"[a-z0-9\\.-]+\"", replace="version = \"{{version}}\""},
]